### PR TITLE
Enhanced Background for new tab

### PR DESCRIPTION
**Pull request by UnknownCoder56**
hi

### CODE REVIEW

**Comment by SLT-World** [comment]
I'll check this out when I get back to my computer.

**Comment by SLT-World** [comment]
Hello, is this pull request still active?

**Comment by SLT-World** [comment]
Pull request closed due to lack to responses and activity.

**Comment by UnknownCoder56** [comment]
Oh I missed all the emails. Sorry about that. Will make another, better
attempt after I reach home.

**Pull request closed without merging**
